/**
 * Phase 8 — Audit Report v2 shared types.
 *
 * The v2 narrative_json shape is what gets persisted on `reports`. v1
 * reports keep their old shape; the public page detects via
 * `narrative_json.version === 2`.
 */

/**
 * Phase 24 — Report fit modes.
 *
 *   high_fit  — current default. Full RCG-pitch report (capture plan,
 *               WHY RCG callouts, strategy-call CTA).
 *   diy_fit   — friendly DIY advice. Triggered when recoverable revenue
 *               < RCG_FIT_MIN_RECOVERABLE_REVENUE (default $500k) AND
 *               brand_controlled_pct ≥ 50% AND no other disqualifier.
 *               Brand already runs a tight channel; pitching RCG fees
 *               wastes both parties' time. We give them three concrete
 *               steps to wrap up the residual reseller share themselves.
 *   not_a_fit — Phase 23 Amazon-1P disqualifier. Persisted as
 *               `reports.status = 'not_a_fit'` (not surfaced in
 *               narrative.report_mode — that state has its own narrative
 *               kind). Listed here for completeness only.
 */
export type ReportMode = "high_fit" | "diy_fit" | "not_a_fit";

export interface NarrativeV2 {
  version: 2;
  generated_at: string;
  brand_id: string;
  brand_name: string;

  /** Phase 24 — render mode. Older reports omit this and default to
   * `high_fit`. */
  report_mode?: ReportMode;
  /** Phase 24 — revenue × (1 − brand_controlled_pct). Persisted so the
   * mode decision is auditable from narrative_json alone. Null when we
   * couldn't compute it (no revenue, or no classification). */
  recoverable_revenue_dollars?: number | null;
  /** Phase 24 — copy of bundle.keepa.brand_controlled_pct at the time of
   * the report, for the same auditability reason. Null when we couldn't
   * classify. */
  brand_controlled_pct?: number | null;

  cover: NarrativeCover;
  reseller_reality: NarrativeResellerReality;
  reseller_dossier: NarrativeResellerDossier | null;
  cx_audit: NarrativeCxAudit;
  competitor_benchmark: NarrativeCompetitorBenchmark;
  math: NarrativeMath;
  plan: NarrativePlan;
  why_rcg: NarrativeWhyRcg;
  cta: NarrativeCta;

  /** Phase 24 — diy_fit-only: the three self-serve steps that replace
   * capture plan + WHY RCG callouts + math in DIY mode. Omitted on
   * high_fit reports. */
  diy_steps?: DiyStep[];

  data_sources: {
    keepa: boolean;
    keepa_freshness: string | null;
    dataforseo: boolean;
    dataforseo_freshness: string | null;
    reseller_dossier: boolean;
    competitor_benchmark: boolean;
  };
}

export interface DiyStep {
  number: number;
  title: string;
  body: string;
}

export interface NarrativeCover {
  headline: string; // ≤ 30 words
  kpis: { label: string; value: string; sub: string | null }[];
  /** Headline economic numbers — populated for v2.1+ "opportunity story"
   * cover. Older reports may have these as null (cover_kpis carries the
   * legacy values). */
  delta_profit?: number | null;
  exit_lift?: number | null;
}

export interface ResellerRow {
  rank: number;
  /** Hotfix May 2026 — nullable. NULL means Keepa couldn't resolve a
   * storefront name for this seller; the renderer surfaces it as
   * "Unknown 3P seller (ID: …)". */
  seller_name: string | null;
  share_pct: number | null;
  asins_won: number | null;
  is_fba: boolean | null;
  country: string | null;
  /** Phase 23 — null on legacy rows, true when the classifier flagged
   * this seller as the brand's own selling entity (e.g. "Fantaswick LLC"
   * for brand "Fantaswick"). */
  is_brand_controlled?: boolean | null;
  /** Phase 23 — short human-readable reason persisted on the row. */
  classification_reason?: string | null;
}

export interface NarrativeResellerReality {
  top_sellers: ResellerRow[];
  one_liner: string; // single sentence beneath the chart
  note: string | null; // null when we don't have enough data
}

export interface DossierAsinRow {
  asin: string;
  title: string | null;
  buy_box_pct: number | null;
  buy_box_price: number | null;
}

export interface NarrativeResellerDossier {
  seller_name: string;
  seller_id: string | null;
  country: string | null;
  share_pct: number | null;
  asins_won: number | null;
  is_fba: boolean | null;
  fulfilment_mix: string; // "FBA dominant" | "FBM dominant" | "Mixed" | "— not measured"
  top_asins: DossierAsinRow[];
  risk_profile: string; // ≤ 200 words, generated by LLM
}

export interface CxAuditAsinScore {
  asin: string;
  title: string | null;
  score: number | null; // 0-100
  bullets: number | null;
  images: number | null;
  has_a_plus: boolean | null;
  has_video: boolean | null;
  reviews: number | null;
  rating: number | null;
  /** Per-ASIN trailing-12-month estimates (Keepa BSR + price). Surface
   * as an amber "Estimate" badge with diligence-replacement footnote. */
  ttm_revenue?: number | null;
  ttm_units?: number | null;
  buy_box_price?: number | null;
  /** Phase 31 — number of siblings sharing the same parentAsin in this
   * brand (including self). 1 for singletons; ≥ 2 means this ASIN is
   * one of a variation family and the per-ASIN revenue reflects the
   * post-attribution number rather than the raw rank-derived
   * estimate. Drives the "Variation (1 of N)" badge. */
  variation_group_size?: number | null;
}

/**
 * Phase 31 — surfaced on `NarrativeCxAudit` so the renderer can decide
 * whether to show the methodology disclosure subsection. True iff at
 * least one ASIN in the brand belongs to a variation group of size ≥ 2.
 */
export interface VariationDisclosure {
  has_variations: boolean;
  /** Default copy is rendered inline; this field is reserved for future
   * per-brand overrides without forcing a renderer change. */
  copy?: string | null;
}

export interface NarrativeCxAudit {
  branded_search_volume: number | null;
  branded_trend_pct: number | null;
  top_keywords: { keyword: string; search_volume: number | null }[];
  asin_scores: CxAuditAsinScore[];
  whats_broken: string[]; // 3 callouts, generated by LLM
  /** Phase 31 — null on legacy reports; populated when the brand has
   * at least one parent variation group (size ≥ 2). The renderer uses
   * `has_variations` to decide whether to show the methodology
   * disclosure. */
  variation_disclosure?: VariationDisclosure | null;
}

export interface CompetitorRow {
  brand: string;
  is_audited_brand: boolean;
  unique_seller_count: number | null;
  brand_controlled_pct: number | null;
  branded_search_volume: number | null;
  organic_serp_rank: number | null;
  listing_health: number | null; // 0-100, average of CX scores
}

export interface NarrativeCompetitorBenchmark {
  rows: CompetitorRow[];
  one_liner: string;
}

export interface MathLine {
  key: string;
  label: string;
  value: number | null; // dollars (or shown as %)
  format: "money" | "percent" | "raw";
  source: string; // "Keepa, 2026-04-15" | "calc: A × B" | "Assumption: 20% margin"
  is_total?: boolean;
  editable?: boolean; // assumption lines are editable per-prospect later
  /** Optional badge rendered next to the value:
   *   "actual"    — green badge (SP-API or imported real number)
   *   "estimate"  — amber badge with diligence-replacement footnote
   *   "confirmed" — Phase 28: user-confirmed TTM revenue from a trusted
   *                 source (Orion, seller call, internal warehouse).
   * Currently only set on the `revenue` row. */
  badge?: "actual" | "estimate" | "confirmed" | null;
  /** Phase 28 — when source='confirmed', the free-text source label the
   *  user typed (e.g. "Orion data"). Internal-only; not rendered on the
   *  public token-share link unless explicitly opted in. */
  confirmed_source?: string | null;
  /** Phase 28 — when source='confirmed', the estimator number we'd
   *  otherwise have shown. Renders as a small inline sub-note
   *  ("Estimator suggested $X"). */
  estimator_suggestion?: number | null;
}

export interface NarrativeMath {
  lines: MathLine[];
  notes: string; // ≤ 50 words
}

export interface PlanColumn {
  label: string; // legacy: "Days 1-30" — v2.1+ uses step-N labels via `steps`
  bullets: string[];
}

export interface PlanStep {
  /** 1-5 — drives ordering & the badge number on the rendered card. */
  number: number;
  /** Webinar's exact step name, e.g. "Identify the Opportunity through an Account Audit". */
  title: string;
  /** Brand-specific 2-3 sentence paragraph (≤ ~50 words) referencing real numbers. */
  body: string;
}

export interface NarrativePlan {
  /** Legacy 90-day three-column shape — kept on older rows. */
  columns: PlanColumn[];
  intro: string; // ≤ 60 words
  /** v2.1+ Five-Step Framework. Older rows render `columns` instead. */
  steps?: PlanStep[];
  /** Closing line under the 5 steps. */
  closing?: string | null;
}

export interface NarrativeWhyRcg {
  bio: string; // ≤ 150 words
  case_studies: { name: string; summary: string; metric: string }[];
  risk_reversal: string; // ≤ 60 words
}

export interface NarrativeCta {
  headline: string;
  primary_cta_url: string | null;
  primary_cta_label: string;
  secondary_email: string;
  secondary_phone: string | null;
}

/**
 * Math framework v4 — World Amenities case-study methodology.
 * Defaults match `LEGION_DEFAULTS` in `src/lib/math/legion-economics.ts`.
 *
 * The legacy split (reseller_margin_pct / ops_savings_pct /
 * mcf_uplift_pct) is gone — `reseller_net_margin_pct` (10.5%) is the
 * single consolidated figure. RCG fees / retainers are no longer
 * computed, persisted, or rendered.
 */
export interface ReportAssumptions {
  reseller_markup_pct: number;        // default 1.03
  outbound_shipping_pct: number;      // default 0.05
  outbound_shipping_payer: "brand" | "reseller" | "unknown"; // default "brand"
  reseller_net_margin_pct: number;    // default 0.105
  current_profit_margin_pct: number;  // default 0.20
  ebitda_multiple: number;            // default 7
  labor_cost_override: number | null; // null → tier rule from revenue
}

export const DEFAULT_ASSUMPTIONS: ReportAssumptions = {
  reseller_markup_pct: 1.03,
  outbound_shipping_pct: 0.05,
  outbound_shipping_payer: "brand",
  reseller_net_margin_pct: 0.105,
  current_profit_margin_pct: 0.20,
  ebitda_multiple: 7,
  labor_cost_override: null,
};
