/**
 * Phase 8 — Audit Report v2 shared types.
 *
 * The v2 narrative_json shape is what gets persisted on `reports`. v1
 * reports keep their old shape; the public page detects via
 * `narrative_json.version === 2`.
 */

export interface NarrativeV2 {
  version: 2;
  generated_at: string;
  brand_id: string;
  brand_name: string;

  cover: NarrativeCover;
  reseller_reality: NarrativeResellerReality;
  reseller_dossier: NarrativeResellerDossier | null;
  cx_audit: NarrativeCxAudit;
  competitor_benchmark: NarrativeCompetitorBenchmark;
  math: NarrativeMath;
  plan: NarrativePlan;
  why_rcg: NarrativeWhyRcg;
  cta: NarrativeCta;

  data_sources: {
    keepa: boolean;
    keepa_freshness: string | null;
    dataforseo: boolean;
    dataforseo_freshness: string | null;
    reseller_dossier: boolean;
    competitor_benchmark: boolean;
  };
}

export interface NarrativeCover {
  headline: string; // ≤ 30 words
  brand_logo_url: string | null;
  kpis: { label: string; value: string; sub: string | null }[];
  /** Headline economic numbers — populated for v2.1+ "opportunity story"
   * cover. Older reports may have these as null (cover_kpis carries the
   * legacy values). */
  delta_profit?: number | null;
  exit_lift?: number | null;
}

export interface ResellerRow {
  rank: number;
  seller_name: string;
  share_pct: number | null;
  asins_won: number | null;
  is_fba: boolean | null;
  country: string | null;
}

export interface NarrativeResellerReality {
  top_sellers: ResellerRow[];
  one_liner: string; // single sentence beneath the chart
  note: string | null; // null when we don't have enough data
}

export interface DossierAsinRow {
  asin: string;
  title: string | null;
  buy_box_pct: number | null;
  buy_box_price: number | null;
}

export interface NarrativeResellerDossier {
  seller_name: string;
  seller_id: string | null;
  country: string | null;
  share_pct: number | null;
  asins_won: number | null;
  is_fba: boolean | null;
  fulfilment_mix: string; // "FBA dominant" | "FBM dominant" | "Mixed" | "— not measured"
  top_asins: DossierAsinRow[];
  risk_profile: string; // ≤ 200 words, generated by LLM
}

export interface CxAuditAsinScore {
  asin: string;
  title: string | null;
  score: number | null; // 0-100
  bullets: number | null;
  images: number | null;
  has_a_plus: boolean | null;
  has_video: boolean | null;
  reviews: number | null;
  rating: number | null;
  /** Per-ASIN trailing-12-month estimates (Keepa BSR + price). Surface
   * as an amber "Estimate" badge with diligence-replacement footnote. */
  ttm_revenue?: number | null;
  ttm_units?: number | null;
  buy_box_price?: number | null;
}

export interface NarrativeCxAudit {
  branded_search_volume: number | null;
  branded_trend_pct: number | null;
  top_keywords: { keyword: string; search_volume: number | null }[];
  asin_scores: CxAuditAsinScore[];
  whats_broken: string[]; // 3 callouts, generated by LLM
}

export interface CompetitorRow {
  brand: string;
  is_audited_brand: boolean;
  unique_seller_count: number | null;
  brand_controlled_pct: number | null;
  branded_search_volume: number | null;
  organic_serp_rank: number | null;
  listing_health: number | null; // 0-100, average of CX scores
}

export interface NarrativeCompetitorBenchmark {
  rows: CompetitorRow[];
  one_liner: string;
}

export interface MathLine {
  key: string;
  label: string;
  value: number | null; // dollars (or shown as %)
  format: "money" | "percent" | "raw";
  source: string; // "Keepa, 2026-04-15" | "calc: A × B" | "Assumption: 20% margin"
  is_total?: boolean;
  editable?: boolean; // assumption lines are editable per-prospect later
  /** Optional badge rendered next to the value:
   *   "actual"   — green badge (SP-API or imported real number)
   *   "estimate" — amber badge with diligence-replacement footnote
   * Currently only set on the `revenue` row. */
  badge?: "actual" | "estimate" | null;
}

export interface NarrativeMath {
  lines: MathLine[];
  notes: string; // ≤ 50 words
}

export interface PlanColumn {
  label: string; // legacy: "Days 1-30" — v2.1+ uses step-N labels via `steps`
  bullets: string[];
}

export interface PlanStep {
  /** 1-5 — drives ordering & the badge number on the rendered card. */
  number: number;
  /** Webinar's exact step name, e.g. "Identify the Opportunity through an Account Audit". */
  title: string;
  /** Brand-specific 2-3 sentence paragraph (≤ ~50 words) referencing real numbers. */
  body: string;
}

export interface NarrativePlan {
  /** Legacy 90-day three-column shape — kept on older rows. */
  columns: PlanColumn[];
  intro: string; // ≤ 60 words
  /** v2.1+ Five-Step Framework. Older rows render `columns` instead. */
  steps?: PlanStep[];
  /** Closing line under the 5 steps. */
  closing?: string | null;
}

export interface NarrativeWhyRcg {
  bio: string; // ≤ 150 words
  case_studies: { name: string; summary: string; metric: string }[];
  risk_reversal: string; // ≤ 60 words
}

export interface NarrativeCta {
  headline: string;
  primary_cta_url: string | null;
  primary_cta_label: string;
  secondary_email: string;
  secondary_phone: string | null;
}

export interface ReportAssumptions {
  reseller_margin_pct: number;        // default 0.20
  ops_savings_pct: number;            // 0.08
  mcf_uplift_pct: number;             // 0.04
  rcg_retainer: number | null;        // dollars/yr — null = placeholder
  ebitda_multiple: number;            // 7
  brand_controlled_pct_override: number | null;
}

export const DEFAULT_ASSUMPTIONS: ReportAssumptions = {
  // v2.1: dropped from 0.20 → 0.10 to land closer to seller-confirmed
  // post-fee blended margin (Amazon takes 15% referral + ~3-5% other,
  // and most brands run 20-25% gross — the recoverable wedge is ~10%).
  reseller_margin_pct: 0.10,
  ops_savings_pct: 0.08,
  mcf_uplift_pct: 0.04,
  rcg_retainer: null,
  ebitda_multiple: 7,
  brand_controlled_pct_override: null,
};
